site_name: Python (2 семестр)
site_url: https://kurotych.com/ua/courses/programming-2sem/
repo_url: https://github.com/kurotych/programming-python-2sem
repo_name: kurotych/programming-python-2sem

watch:
  - docs

theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.sections
    - navigation.expand
    - toc.integrate
    - content.code.copy

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

copyright: 2026 Куротич Анатолій. Всі права захищені.

extra:
  analytics:
    provider: google
    property: G-HKDH744EMY
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/kurotych

nav:
  - Головна: index.md
  - Модуль 1:
    - module1/01-sqlite-lecture.md
    - module1/02-sqlite-practice.md
    - module1/03-psycopg2-lecture.md
    - module1/04-psycopg2-practice.md
    - module1/05-alembic-lecture.md
    - module1/06-alembic-practice.md
    - module1/07-error-handling-transactions-lecture.md
    - module1/08-error-handling-transactions-practice.md


